// automatically generated by the FlatBuffers compiler, do not modify

package string_multimap

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// simple simili-multimap type for Flatbuffers
/// map entry
/// maps a key to a number of values
/// id: string
/// values: array of strings
type MapEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsMapEntry(buf []byte, offset flatbuffers.UOffsetT) *MapEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MapEntry{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *MapEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MapEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MapEntry) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MapEntry) Values(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *MapEntry) ValuesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MapEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MapEntryAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func MapEntryAddValues(builder *flatbuffers.Builder, values flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(values), 0)
}
func MapEntryStartValuesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MapEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
